### ISSUE TITLE
wasi component runtime error: instance export `read` has the wrong type

### ISSUE THREAD

**Issue by kajacx** [bytecodealliance/cargo-component#105]
After installing a the newest version of `cargo component`, I get this error:

```
Error: import `wasi:io/streams` has the wrong type

Caused by:
    0: instance export `read` has the wrong type
    1: type mismatch with results
    2: expected `bool` found `enum`
```

Full reproducible example can be found [here](https://github.com/kajacx/wasm-playground/blob/wasi-imports-type-problems/runtime-rust-wasmtime/src/main.rs). Look at the `plugin-wasi` for the guest code and `runtime-rust-wasmtime` for the host. The `build-and-run-sys.sh` script shows what commands I use to build the guest and run the host.

**Comment by peterhuene** [comment]
The WASI adapter built into `cargo-component` is slightly newer than 11.0 (it's currently using commit `7b9189b`), so the signatures aren't matching.

The easiest workaround is to use a matching wasmtime-wasi and wasmtime.

`cargo-component` needs a way to override the built-in adapters with explicitly specified ones, though. Let's track that as part of this issue.

**Comment by peterhuene** [comment]
Also, I expect to start sourcing the adapters from a registry so that the version can be specified in `Cargo.toml` (defaults to latest available, probably).

We're almost to the point where WASI wit packages and the adapters can be published.

**Comment by kajacx** [comment]
> The easiest workaround is to use a matching wasmtime-wasi and wasmtime.

Ok, I managed to do that when using wasmtime from source. I will put a [link to the code](https://github.com/kajacx/wasm-playground/commit/7c164ff42510e3c8439cb519cb9008d23b47a161) here in case anyone runs into the same issue, but it's kind of a mess.
