### ISSUE TITLE
`cargo-component` overwrites WIT package version with `Cargo.toml` version

### ISSUE THREAD

**Issue by kate-goldenring** [bytecodealliance/cargo-component#111]
`cargo-component` seems to automagically set a component's interface version to be that of the Cargo project rather than using the version (or lack of version specified in the WIT interface). 

## What works
The standard "hello, world" example that does not use an interface works as expected:

```bash
$ cargo component new --reactor example
$ cd example
$ cargo component build
$ wasm-tools print target/wasm32-wasi/debug/example.wasm | tail
(type (;13;) (func (result string)))
  (alias core export 2 "hello-world" (core func (;33;)))
  (alias core export 2 "cabi_post_hello-world" (core func (;34;)))
  (func (;14;) (type 13) (canon lift (core func 33) (memory 0) string-encoding=utf8 (post-return 34)))
  (export (;15;) "hello-world" (func 14))
  (@producers
    (processed-by "wit-component" "0.13.1")
    (processed-by "cargo-component" "0.1.0 (26e55d8 2023-08-15 wasi:2750b73)")
  )
)%

```
Function `hello-world` is exported as expected. 

## What does not work
However, if the WIT is updated to export the `hello-world` function from an interface, `cargo-component` automatically appends a version suffix to the interface to match that of the `Cargo.toml`. For example, if you change the WIT to:

```bash
package component:example

interface foo {
    hello-world: func() -> string
}

world example {
    export foo
}
```

And update the implementation in `lib.rs` to:

```bash
cargo_component_bindings::generate!();

use bindings::exports::component::example::foo::Foo;

struct Component;

impl Foo for Component {
    /// Say hello!
    fn hello_world() -> String {
        "Hello, World!".to_string()
    }
}
```

After rebuilding, you will see that the version `0.1.0` is attached to the interface automagically by `cargo-component`:

```bash
$ cargo component build
$ wasm-tools print target/wasm32-wasi/debug/example.wasm | tail
(instance (;8;) (instantiate 0
      (with "import-func-hello-world" (func 14))
    )
  )
  (export (;9;) (interface "component:example/foo@0.1.0") (instance 8))
  (@producers
    (processed-by "wit-component" "0.13.1")
    (processed-by "cargo-component" "0.1.0 (26e55d8 2023-08-15 wasi:2750b73)")
  )
)%
```

After updating the version in `Cargo.toml` to `"0.2.0"` and rebuilding, the version is now `0.2.0`:

```bash
$ cargo component build
$ wasm-tools print target/wasm32-wasi/debug/example.wasm | tail
(instance (;8;) (instantiate 0
      (with "import-func-hello-world" (func 14))
    )
  )
  (export (;9;) (interface "component:example/foo@0.2.0") (instance 8))
  (@producers
    (processed-by "wit-component" "0.13.1")
    (processed-by "cargo-component" "0.1.0 (26e55d8 2023-08-15 wasi:2750b73)")
  )
)%
```

Even if i set the package version in the WIT `package component:example@0.5.0`, the version from the `Cargo.toml` is set on the component interface.

This becomes problematic when writing a Rust program that uses the component, referencing the WIT (`wasmtime::component::bindgen!("example" in "world.wit");`). It cannot find the instance due to mismatched versioning and errors with:

```bash
Error: instance 'example:service/handler' not found
```

**Comment by peterhuene** [comment]
If the version in `Cargo.toml` matches an explicit version in the `package` directive, is `wasmtime::component::bindgen!` importing the right interface?

If the versions don't match, `cargo-component` could at least emit an error to prevent encountering the problem at runtime, but I really don't like having multiple sources of truth for the version.

That said, I'm really hoping an updated design for WIT that we're currently working on for using it to define component compositions with does away with the `package` directive, as, to me at least, it does not play well with tooling intended to resolve versions from external sources (e.g. a well-known location like `Cargo.toml` or a registry with respect to dependencies).

We will eventually need think of how the `bindgen!` macro could consume worlds published to a registry (or encoded in a binary format rather than just WIT files, at the very least).

**Comment by kate-goldenring** [comment]
> If the version in Cargo.toml matches an explicit version in the package directive, is wasmtime::component::bindgen! importing the right interface?

Yes. Adding the explicit version to the package directive resolves this.

> If the versions don't match, cargo-component could at least emit an error to prevent encountering the problem at runtime

Maybe we could emit a build failure here instead. However, i am not sure i understand why we are considering the Rust package version at all. Why do we care if the component's version matches the Rust package version? To me the version of the interface that a component implements is different from the version of the Rust package that is resolved to the component, since i could choose to implement the component in different ways, prompting a bump in the Cargo version but no change in the WIT version. Could we ignore the Cargo package version during a `cargo component build`?

**Comment by peterhuene** [comment]
Great questions!

> Maybe we could emit a build failure here instead?

Indeed, that's how it would appear if `cargo-component` simply errors on generating bindings for a mismatched `package` directive; the `cargo component build` command would error before even spawning `cargo build`.

> However, i am not sure i understand why we are considering the Rust package version at all. Why do we care if the component's version matches the Rust package version?

The version in `Cargo.toml` is treated as the version for the _component_ being authored; it is the version of the component if you publish it (the component's wasm file) to a registry with `cargo component publish`. One wouldn't publish the Rust package to `crates.io` as these aren't really useful as Rust crates. 

That said, specifying a local target path for the component being authored has two primary use cases: 

1. To bootstrap building components before the existence of a component registry, the place where one would normally target shared interface and world definitions; although support for targeting a world from a registry is already implemented in `cargo-component`, we're still a little ways off from having a live registry for everyone to use (getting close, though!).

2. Specifying a custom world for the component to target; in this use case one would still use interface definitions from the registry and not define interfaces in your WIT unless you wanted them to be local to the component. This concept of "local" interfaces is why `cargo-component` is specifying that they come from the component being authored and using the component's version as a result. In the future, this would be the only use case for a local target.

The requirement on parsing WIT files for various tooling is to workaround for the absence of a registry; it's not the ultimate design goals of the tooling, though. My sincere hope is that, in the future, we have registry-aware tooling for generating host bindings much like `cargo-component` is registry-aware for generating guest bindings.

**Comment by peterhuene** [comment]
Hi @kate-goldenring.

After more thought on this, I've put up #130 that removes the implicit versioning of the WIT based on `Cargo.toml`.

Now the version in `Cargo.toml` is the component (and package, if published to a registry) version and the WIT versions are entirely independent.

This should eliminate this footgun between `cargo-component` and Wasmtime's `bindgen!` macro.

**Comment by kate-goldenring** [comment]
Thanks @peterhuene!
