### ISSUE TITLE
Failure to build component containing flags shape

### ISSUE THREAD

**Issue by eduardomourar** [bytecodealliance/cargo-component#119]
I am using cargo-component from commit 29fea4af8a28857e6a1fee3df3cd930a3fadad10.

While trying to build a component that contains a `flags` shape (example [here](https://github.com/bytecodealliance/cargo-component/blob/dab8fe09e1f43f7b47aaaa40b275078864f37a7d/example/wit/example.wit)), the following error is presented (reproduced [here](https://github.com/bytecodealliance/cargo-component/actions/runs/5908361401/job/16027700973?pr=118)):
> error[E0433]: failed to resolve: use of undeclared crate or module `wit_bindgen`
 --> src/lib.rs:1:1
  |
1 | cargo_component_bindings::generate!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `wit_bindgen`
  |
  = note: this error originates in the macro `cargo_component_bindings::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0412]: cannot find type `Permissions` in this scope
 --> src/lib.rs:1:1
  |
1 | cargo_component_bindings::generate!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
  = help: consider importing this struct:
          std::fs::Permissions
  = note: this error originates in the macro `cargo_component_bindings::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0433]: failed to resolve: use of undeclared type `Permissions`
 --> src/lib.rs:1:1
  |
1 | cargo_component_bindings::generate!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `Permissions`
  |
  = help: consider importing this struct:
          std::fs::Permissions
  = note: this error originates in the macro `cargo_component_bindings::generate` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by peterhuene** [comment]
It looks like I might have missed a place where the generated code was assuming `wit_bindgen` for the runtime path.

I'll get this fixed in upstream `wit-bindgen` and resolve this issue once we get it patched.

**Comment by peterhuene** [comment]
This [line](https://github.com/bytecodealliance/wit-bindgen/blob/e32a150f876c291784d9cead97c58fac97cf216c/crates/rust/src/lib.rs#L1284) is the problem. Looks like we should also be reexporting `bitflags` from `cargo_component_bindings` as well.

**Comment by peterhuene** [comment]
I've put up https://github.com/bytecodealliance/wit-bindgen/pull/645 to address this; once that merges, a small change is required to `cargo-component` to resolve the issue.
