### ISSUE TITLE
Investigation: using `witgen` for default interface definitions?

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/cargo-component#12]
Right now we create a `interface.wit` file to represent the _default_ interface of the component (i.e. what the component itself exports as functions rather than named instances).

There's a really cool effort underway to use proc-macros to generate `wit` files from Rust types called [witgen](https://github.com/bnjjj/witgen).

It would be really fantastic if Rust developers could author at least their default interface definitions using Rust types, if desired, as that would be a pretty natural fit for DX.

**Comment by jakehemmerle** [comment]
It seems like witgen is particularly outdated. Would it make more sense to integrate .wit-from-Rust generation here?
