### ISSUE TITLE
cargo-component.lock file created everywhere

### ISSUE THREAD

**Issue by jessbowers** [bytecodealliance/cargo-component#124]
I'm getting a cargo-component.lock file created on almost every project I open in VSCode. I'm not sure why this is happening, but I was curious if it's something that can be suppressed/disabled?

**Comment by peterhuene** [comment]
Currently there is no way to suppress the generation of the lock file, although we can potentially omit writing one if the dependency list is empty, at least.

The purpose of the file is to serve as a place to lock dependency versions from a component registry, analogous to how `Cargo.lock` locks dependencies from `crates.io`.

**Comment by jessbowers** [comment]
I think that would be a good idea. Otherwise every rust project I open is getting this additional, unnecessary file.
