### ISSUE TITLE
Could the `wit` folder be included by default without any configuration?

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/cargo-component#134]
Similar to how Cargo supports `src/bin/*.rs` or `src/lib.rs` without configuration, the idea being that a conventional structure of a project doesn't require further configuration but config is always possible. To that effect would the `wit/*.wit` folder be loaded by default and made available for bindings?

**Comment by peterhuene** [comment]
Makes sense to me to default the target to a `wit` directory and not require that the directory exists.
