### ISSUE TITLE
Adding custom derive attributes

### ISSUE THREAD

**Issue by thomastaylor312** [bytecodealliance/cargo-component#148]
Wit bindgen recently merged support for adding custom derive attributes: https://github.com/bytecodealliance/wit-bindgen/pull/678. Is that something that can be exposed in `cargo component`? I'm fine to do the work, just need a little bit of direction about where it would belong

**Comment by peterhuene** [comment]
I think this is totally doable.

The `generate!` macro already has a bunch of different argument, so I think we just need to expose this similar to the `wit-bindgen::generate!` macro.

Happy to pair with you tomorrow if you're around.

**Comment by thomastaylor312** [comment]
I think I may have figured out where to put it? I'll give it a try and then might steal some pairing time if I can't get it
