### ISSUE TITLE
issue installing cargo-component  “note: perhaps two different versions of crate wit_parser are being used"

### ISSUE THREAD

**Issue by jennypollack** [bytecodealliance/cargo-component#154]
```
=` note: `wit_parser::PackageName` and `PackageName` have similar names, but are actually distinct types
note: `wit_parser::PackageName` is defined in crate `wit_parser`
   --> /Users/jennypc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-parser-0.12.0/src/lib.rs:126:1
    |
126 | pub struct PackageName {
    | ^^^^^^^^^^^^^^^^^^^^^^
note: `PackageName` is defined in crate `wit_parser`
   --> /Users/jennypc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-parser-0.11.3/src/lib.rs:126:1
    |
126 | pub struct PackageName {
    | ^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `wit_parser` are being used?

error[E0308]: mismatched types
```

apologies as i'm relatively new to rust and having trouble finding the 0.12.0 version - anyone have an idea how i can resolve?

i was also looking to see if i could install an older version of cargo-component but seems it's no longer there? https://crates.io/crates/cargo-component/0.1.0

**Comment by peterhuene** [comment]
Hi @jennypollack.

Sorry about that!

It appears that there's an updated `wit-parser` crate but the `wit-bindgen` crates haven't been published yet.

To work around this for now, supply the `--locked` argument when installing: `cargo install --locked cargo-component`.

That will prevent cargo from trying to roll forward cargo-component's dependencies.

This should go away once `wit-bindgen` is published.

**Comment by jennypollack** [comment]
thanks that worked!
