### ISSUE TITLE
Consider adding binaries to the release artifacts

### ISSUE THREAD

**Issue by morenol** [bytecodealliance/cargo-component#159]
Can we add `cargo-component` binaries in the release artifacts? I can work on that

**Comment by peterhuene** [comment]
I don't see why not. Thanks for taking that on!

**Comment by peterhuene** [comment]
@morenol It looks like the linux one failed: https://github.com/bytecodealliance/cargo-component/actions/runs/6644604756/job/18054113468#step:7:5

**Comment by morenol** [comment]
Checking it now
