### ISSUE TITLE
`check` doesn't seem to generate the file bindings

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/cargo-component#170]
Hi, and thanks again for this tool.

I was using the `cargo component check` in CI but it started failing after upgrading `cargo-component` to 0.4.0:

```
error: bindings file `/home/runner/work/trinity/trinity/modules/target/bindings/uuid/bindings.rs` does not exist
       
       did you forget to run `cargo component build`? (https://github.com/bytecodealliance/cargo-component)
```

Is that expected that one needs to build before running the check command? The `check` command is quite faster than `compile`, although in my case I don't really care about the difference since that is running in CI.

**Comment by peterhuene** [comment]
The check command should be generating the file. Let me look into it.

**Comment by peterhuene** [comment]
It works here as I would expect and we have test coverage for the command.

To verify, what's the `--version` output of `cargo-component` and what version of `cargo-component-bindings` is being referenced in `Cargo.toml` for the project?

Was there a "Generating bindings for <name>" message printed (should be the first one in the output, typically)?

This is the error I would expect if `cargo-component-bindings` was bumped to `0.4.0` but `cargo-component` itself remained at a previous version.

**Comment by peterhuene** [comment]
Unrelated to the issue here, but the error coming from the macro should probably just be "did you forget to run `cargo component <command>`?" rather than assume the command was build. I'll fix that in the hopes that it reduces the confusion that build must be run.

**Comment by bnjbvr** [comment]
My bad, I got the error in a Github CI action and that was because the Rust cache action cached the `.cargo/bin` binaries, so I was using an old version. Clearing the cache fixed it :+1:
