### ISSUE TITLE
How to build `wat` for preview?

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/cargo-component#179]
In addition to generating binary `wasm`, can the build command generate a readable `wat` interface?

I tried using wasmer to export wat, but it didn't work:

```rust
InvalidWasm { error: "Bad version number (at offset 4)" }
```

**Comment by tschneidereit** [comment]
Components are a new binary format that Wasmer chose not to support, which is why you're getting this error message.

To run components you can use Wasmtime. To convert a component into a wat file, you can use `wasm-tools print`.

**Comment by oovm** [comment]
Thanks, works good
