### ISSUE TITLE
Rust-analyzer doesn't integrate bindings in workspace

### ISSUE THREAD

**Issue by vwkd** [bytecodealliance/cargo-component#196]
IntelliSense with rust-analyzer is broken in a workspace. The bindings in `target/bindings` are generated, but when expanding the macro recursively they aren't.

## Steps To Reproduce

1. Create workspace with one library crate. Minimal example: [cargo-component-rust-analyzer-workspace](https://github.com/vwkd/cargo-component-rust-analyzer-workspace).
1. Open repo in VSCode.
1. Confirm bindings are generated in [target/bindings/foo/bindings.rs](target/bindings/foo/bindings.rs#L6) automatically by rust-analyzer.
1. Confirm no IntelliSense when cursor is placed over `api::Guest` trait in [foo/src/lib.rs#L6](foo/src/lib.rs#L6).
1. Confirm running command "rust analyzer: Expand macro recursively at caret" gives empty `bindings` when cursor is placed over `cargo_component_bindings::generate!()` macro in [foo/src/lib.rs#L1](foo/src/lib.rs#L1).

## Versions

- VSCode `1.84.2`
- rust-analyzer extension `v0.3.1740`
- `cargo-component` package `0.4.1`

## Additional Information

The same issue occurs to me sometimes in a non-workspace library crate, but I can't reproduce it reliably. It seems like some random combination of restarting rust-analyzer, deleting the `target` directory, and changing `Cargo.toml` can fix it, and also break it again.

Continued from https://github.com/bytecodealliance/cargo-component/issues/139#issuecomment-1820609274

**Comment by peterhuene** [comment]
From the output of RA:

```
File with cargo diagnostic not found in VFS: file not found: /Users/peterhuene/demo/target/bindings/proxy/bindings.rs
```

It seems, for whatever reason when loaded in a workspace, the VFS isn't populated with the bindings file, which I think means RA will give it an empty file to the proc-macro, ultimately resulting in an empty bindings macro.
