### ISSUE TITLE
How to use cargo-component for subprojects?

### ISSUE THREAD

**Issue by k82cn** [bytecodealliance/cargo-component#202]
Is there anyway to build one of subprojects by cargo-component? In my environment, my project includes wasmtime engine/executor and wasm application; I'd like to build them in one project. Currently, I exclude wasm application build in the workspace, and build it manually by `cargo component build`.

xref: https://github.com/xflops/flame/tree/main/examples/matrix

**Comment by peterhuene** [comment]
Hi @k82cn. Unfortunately, `cargo` currently only supports a single target applied to the entire workspace (there's an unstable ["per-package" target feature](https://doc.rust-lang.org/cargo/reference/unstable.html#per-package-target), but that's not available yet).

So unfortunately you'll need two workspaces: one for the host and one for any components.

**Comment by k82cn** [comment]
Ok, got that. Thanks :)
