### ISSUE TITLE
Generate better cargo check command for vscode

### ISSUE THREAD

**Issue by tomasol** [bytecodealliance/cargo-component#203]
I propose replacing the contents of `.vscode/settings.json` 
```json
{
    "rust-analyzer.check.overrideCommand": ["cargo", "component", "check", "--message-format=json"]
}
```
with
```json
{
    "rust-analyzer.check.overrideCommand": [
        "cargo",
        "component",
        "check",
        "--workspace",
        "--all-targets",
        "--message-format=json"
    ],
}
```
This works well even if the project is not part of a workspace, and the parameters are mentioned in the [User Maunal](https://rust-analyzer.github.io/manual.html) as the default:

> By default, a cargo invocation will be constructed for the configured targets and features, with the following base command line:
> `cargo check --quiet --workspace --message-format=json --all-targets`

The main benefit is that the current setting skips checking tests, benches etc.

**Comment by peterhuene** [comment]
@tomasol Thanks for the suggestion! That sounds like what we should be using then.

Would you be up for changing it to your suggestion in `src/commands/new.rs` (`create_editor_settings_file`) and submit a PR?
