### ISSUE TITLE
Cannot build component using `no_std` after v0.7.0

### ISSUE THREAD

**Issue by greenhat** [bytecodealliance/cargo-component#226]
After upgrading to `cargo-component` v0.7.0, I cannot build a component that uses `#![no_std]` attribute. 

The first issue is that panic handler and global allocator is now required to build the core Wasm module. Is this an expected behaviour? 

The second issue is `memcpy` is compiled as Wasm module import rather than Wasm `memory.copy`.

I made a minimal case for reproducing the issue at https://github.com/greenhat/cargo-component-v0.7-no-std-repr repo. Here is the README where I described the issue copied from there:

### Minimal case for reproducing cargo-component v0.7 (rust 1.75) breakage of `#![no_std]` in components.

1. After generating the project with `cargo component new --lib test-lib` when adding `#![no_std]` to `lib.rs`, the `cargo-component` build fails with:

```text
❯ cargo component build --release
   Compiling test-lib v0.1.0 (/Users/dzadorozhnyi/src/cargo-component-v0.7-no-std-repr)
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait

error: `#[panic_handler]` function required, but not found

error: could not compile `test-lib` (lib) due to 2 previous errors
```

2. When adding a global allocator and panic handler, the build fails with:

```text
❯ cargo component build --release
  Generating bindings for test-lib (/Users/dzadorozhnyi/src/cargo-component-v0.7-no-std-repr/src/bindings.rs)
   Compiling wee_alloc v0.4.5
   Compiling cfg-if v0.1.10
   Compiling memory_units v0.4.0
   Compiling test-lib v0.1.0 (/Users/dzadorozhnyi/src/cargo-component-v0.7-no-std-repr)
    Finished release [optimized] target(s) in 1.31s
    Creating component /Users/dzadorozhnyi/src/cargo-component-v0.7-no-std-repr/target/wasm32-wasi/release/test_lib.wasm
error: module requires an import interface named `env`
```

Which happens because `memcpy` is expected to be imported from `env` while before it was compiled to Wasm `memory.copy` instruction.
See [debug.wat](https://github.com/greenhat/cargo-component-v0.7-no-std-repr/blob/main/debug.wat) (generated with `wasm-tools print target/wasm32-wasi/release/test_lib.wasm > debug.wat`) for the wat of the generated Wasm module. The import is `(import "env" "memcpy" (func $memcpy (;0;) (type 1)))`

**Comment by peterhuene** [comment]
Hi @greenhat. What version of `cargo-component` and Rust did this work on before?

I'm not aware of any changes to `cargo-component` that might have effected `no_std` codegen.

**Comment by greenhat** [comment]
Hi @peterhuene! Thanks for the quick response! It works on `cargo-component` v0.6.0. We are using Rust `nightly-2023-12-20`, but I also tested it on v1.75.0 with the same result.

**Comment by peterhuene** [comment]
When using `0.6.0`, were you using `wit-bindgen::generate!` directly or `cargo_component_bindings::generate!`, as the latter was never made `no_std`?

Sorry for asking a lot here, but would it be possible to have a repro that works in 0.6.0 as-is? Thanks!

**Comment by greenhat** [comment]
> When using `0.6.0`, were you using `wit-bindgen::generate!` directly or `cargo_component_bindings::generate!`, as the latter was never made `no_std`?

I'm using the "default" way - `cargo_component_bindings::generate!`.

> 
> Sorry for asking a lot here, but would it be possible to have a repro that works in 0.6.0 as-is? Thanks!

Sure. No problem! Thanks for looking into this! Here is the repo for the minimal `no_std` example working fine with v0.6 - https://github.com/greenhat/cargo-component-v0.6-no-std-repr

**Comment by peterhuene** [comment]
Hi @greenhat.

So what I think was happening here is that `cargo_component_bindings` was not being built correctly for `no_std`, so my guess is that it was incidentally linking in the stdlib allocator.

With 0.7.0, the removal of `cargo_component_bindings` meant that your `no_std` crate just depended on `wit-bindgen`, which _is_ intentionally using `alloc` to be `no_std` compatible; that is why an allocator / panic handler must now be specified when your component is `no_std`.

The `memcpy` import appears to come from the `__rust_realloc` that is emitted when `#[global_allocator]` is used; you may need to provide your own implementation to prevent it from being imported:

```rust
#[no_mangle]
pub unsafe extern fn memcpy(dest: *mut u8, src: *const u8, n: usize) -> *mut u8{
    // ...
}
```

**Comment by greenhat** [comment]
Thank you, Peter, for the quick and detailed response! 

> So what I think was happening here is that `cargo_component_bindings` was not being built correctly for `no_std`, so my guess is that it was incidentally linking in the stdlib allocator.

It makes sense. `dlmalloc` caught my eye in the compiled wasm binary with v0.6, but I have not investigated it further.
