### ISSUE TITLE
`cargo component new` in Workspace no longer works (`wit-bindgen` v`0.19.1`)

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/cargo-component#241]
Ever since `wit-bindgen` version `v0.19.1` I have been having issues in a Cargo Workspace doing:

```
# workspace/crates
cargo component new --lib my-project
```

The log is:

```sh
error: cannot override workspace dependency with `--default-features`, either change `workspace.dependencies.wit-bindgen.defa
ult-features` or define the dependency exclusively in the package's manifest
error: `cargo add` command exited with non-zero status
```

with
```toml
[workspace.dependencies]
wit-bindgen = { version = "0.19.2", default-features = false, features = ["realloc"] }
```

I'm not quite sure what's going on, but recently we had a problem with `0.19.1` that was fixed by this patch in `0.19.2`:

See: https://github.com/bytecodealliance/wit-bindgen/issues/864 

Not sure if bumping the dep will fix the workspace issue, but it might?

**Comment by DougAnderson444** [comment]
@benwis perhaps you're seeing workspace issues too?

**Comment by peterhuene** [comment]
Also note that we hope to remove the `wit-bindgen` dependency from user projects in the future, with work already done to prevent the kind of breakage that 0.19.x introduced; at a minimum, we might have a dependency on a tiny "canonical exports" crate that can be built without having to muck with features.

**Comment by peterhuene** [comment]
With https://github.com/bytecodealliance/wit-bindgen/pull/876 and the new `wit-bindgen-rt` crate published in the near future, `cargo-component` projects will then have only direct dependencies on `bitflags` (for the generated bindings) and `wit-bindgen-rt` (for exporting required canonical ABI functions).

This should help fix this particular issue!

**Comment by peterhuene** [comment]
I verified that with these changes we get the expected behavior of `cargo component new` inside of a workspace where the dependencies are already specified:

```toml
bitflags = { workspace = true }
wit-bindgen-rt = { workspace = true }
```

**Comment by DougAnderson444** [comment]
@peterhuene you rock!
