### ISSUE TITLE
Support WASI Preview 2 

### ISSUE THREAD

**Issue by NukeManDan** [bytecodealliance/cargo-component#242]
In the README:

> When the Rust compiler supports a [_preview2_ version of the WASI target](https://github.com/rust-lang/compiler-team/issues/594),
support in `cargo component` for adapting a _preview1_ module will be removed.

https://github.com/WebAssembly/WASI/pull/577 IIUC now WASI has launched support for preview 2 :tada: - is there some plan/timeline for cargo component to update to use it? Anything some eager new contributors might be able to help with? :grin:

**Comment by NukeManDan** [comment]
I see https://github.com/rust-lang/rust/pull/119616 is landing _at this moment_ to have `wasm32-wasi-preview2` as a target :sweat_smile: - enabling cargo contract to use it in nightly very soon I would think :crossed_fingers:

**Comment by jeffparsons** [comment]
That PR has merged now, but IIRC it's still mostly just boilerplate, and there's more work before it can be meaningfully used as a way to target WASIp2. E.g. actually creating a Wasm Component from the resulting binary.

**Comment by peterhuene** [comment]
Hi @NukeManDan.

Thanks for the issue! `cargo-component` already supports WASI 0.2.0 (a.k.a. "preview2").

`cargo-component` supports it in a few ways:

1) If you use Rust's stdlib, the Rust toolchain will emit a preview1 compatible module; `cargo-component` automatically adapts the preview1 interface into a preview2 interface when creating the component.

2) You may use the `wasi` crate to directly interact with WASI preview2; this crate wraps generated bindings, giving a more consistent API.

3) You may target the WASI 0.2.0 WIT packages directly from your component and `cargo-component` will generate bindings for you to call WASI imports.

When the Rust toolchain supports WASI 0.2.0, it will simplify the first item above by no longer having to adapt the module from preview1.
