### ISSUE TITLE
Issues with `-` vs `_` translation

### ISSUE THREAD

**Issue by NukeManDan** [bytecodealliance/cargo-component#250]
I have a tiny demo to play with components, and noticed a few issues with respect to `-` vs `_` in a few places:

- [In package names](https://github.com/NukeManDan/wasi-demo/commit/d3134a3abb56a6d9434c4efa8d689dcb9c883a5c#r139411030)
- [In fn signatures](https://github.com/NukeManDan/wasi-demo/blob/84ddcfc261057ae00b7481bdaf991d1a7436f3f6/utils/src/lib.rs#L21) translated [to/from `.wit`](https://github.com/NukeManDan/wasi-demo/blob/84ddcfc261057ae00b7481bdaf991d1a7436f3f6/wit/responder.wit#L4) 
  ```
  Creating component target/wasm32-wasi/release/utils.wasm
  error: failed to validate exported interface `ss:utils/base64@0.1.0`

  Caused by:
      module does not export required function `ss:utils/base64@0.1.0#decode-str`
  ```
Am I missing something simple here, or is it known there are some bugs in converting conventions/cases in signatures?

---

### Using

- cargo-component-component 0.9.1 (wasi:ab5a448)
- wit-bindgen-rt = "0.21.0"

**Comment by peterhuene** [comment]
Hi @NukeManDan.

This error usually indicates a missing call to the generated `bindings::export!` macro, which might be the case if you upgraded from a version of `cargo-component` older than `0.9.0`.

In your [`src/lib.rs` for the `utils` component](https://github.com/NukeManDan/wasi-demo/blob/main/utils/src/lib.rs) I think you need to add the following:

```rust
bindings::export!(Component with_types_in bindings);
```

Let me know if that doesn't do the trick!

**Comment by NukeManDan** [comment]
:partying_face: indeed it was a simple fix for the function signature issue!

I forgot the detail on the package issue that remains though:
- cargo package = `ss-util`
- generated wasm = `.../target/wasm32-wasi/release/ss_utils.wasm`

Strangely, using `ss-cli` yields `ss-cli.wasm` as an artifact :shrug: 

See it [here](https://github.com/NukeManDan/wasi-demo/compare/build-file-name-issue?expand=1#diff-be66a7c8cc643dffaf26a57da4cb33a32a8d5e3bf5d8494dd17a9b2d48b7ff2eR2)

**Comment by peterhuene** [comment]
Unfortunately, for `lib` projects, `cargo` [replaces `-` with `_`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-name-field).

That documentation appears incorrect as I see the same behavior as you for `src/main.rs` (with simply `cargo new bin-foo && bin-foo && cargo build` vs. `cargo new --lib lib-foo && cd lib-foo && cargo build`), where the hyphens are maintained in the output name.

**Comment by NukeManDan** [comment]
So an upstream issue... Thanks for spotting! https://github.com/rust-lang/cargo/issues/13541 I hope we can resolve it

Thanks for the super fast support here as well! :superhero:
