### ISSUE TITLE
Build fails with "no entry found for key" panic from `wit-bindgen`

### ISSUE THREAD

**Issue by mkovaxx** [bytecodealliance/cargo-component#252]
## Setup to Reproduce

https://github.com/mkovaxx/wasm-component-problem

## Error

```
$ RUST_BACKTRACE=1 cargo component build --package cli   
  Generating bindings for cli (components/cli/src/bindings.rs)
thread 'main' panicked at /Users/mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-bindgen-rust-0.20.0/src/interface.rs:1764:73:
no entry found for key
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: wit_bindgen_rust::interface::InterfaceGenerator::path_to_interface
   4: wit_bindgen_rust::interface::InterfaceGenerator::type_path_with_name
   5: wit_bindgen_rust::interface::InterfaceGenerator::print_ty
   6: wit_bindgen_core::InterfaceGenerator::define_type
   7: <wit_bindgen_rust::RustWasm as wit_bindgen_core::WorldGenerator>::import_interface
   8: wit_bindgen_core::WorldGenerator::generate
   9: cargo_component::run_cargo_command::{{closure}}
  10: cargo_component::main::{{closure}}
  11: cargo_component::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Overview

```
% tree
.
├── Cargo.lock
├── Cargo.toml
├── README.md
├── components
│   ├── cli
│   │   ├── Cargo.toml
│   │   └── src
│   │       └── main.rs
│   ├── parser
│   │   ├── Cargo.toml
│   │   ├── src
│   │   │   ├── bindings.rs
│   │   │   └── lib.rs
│   │   └── wit
│   │       └── parser.wit
│   └── types
│       └── wit
│           └── types.wit
└── rust-toolchain
```

## Version Info

```
$ cargo component --version
cargo-component-component 0.9.0 (wasi:ab5a448)

$ cat rust-toolchain
1.75.0
```

## Steps to Reproduce

```
cargo component build --package parser
cargo component build --package cli
```

**Comment by peterhuene** [comment]
I've reproduced the error and I'm investigating.

**Comment by peterhuene** [comment]
It appears the code that turns a component dependency's exports into imports isn't properly handling used types in exported interfaces, only types directly exported by the component.

As such, the target world it is creating isn't valid for bindings generation, which trips up `wit-bindgen`.

I should have a fix this tomorrow.

**Comment by mkovaxx** [comment]
Thanks for looking into this! :)

Not sure if it's helpful, but I have a branch up to show a workaround that seems to solve the issue:
https://github.com/mkovaxx/wasm-component-problem/pull/1/files

**Comment by mkovaxx** [comment]
@peterhuene Thank you for the guidance and detailed explanation here! 🙏 

One more question came to mind. Are there plans to support private component registries, or tooling to run a registry locally?

**Comment by peterhuene** [comment]
Yes, we will have support for both private and self-hosted registries, whether they be warg-based or (with support coming soon) OCI registries.
