### ISSUE TITLE
Question: Should `bindings.rs` be tracked by version control, or ignored?

### ISSUE THREAD

**Issue by mkovaxx** [bytecodealliance/cargo-component#255]
Couldn't find advice on this in the documentation.

## Details

Let's say I initialized a new component project with `cargo component new`, so I have a tree like this:
- `new-shiny-thing`
  - `src`
    - `bindings.rs`
    - `lis.rs`
  - `wit`
    - ...
  - `Cargo.toml`
  - ...

Building the project will generate `src/bindings.rs`.
Should that be tracked by version control, or should it be ignored?

**Comment by peterhuene** [comment]
I think either approach would be fine, although it's a generated file and the changes are dependent on the `cargo-component` version, so ignoring it makes more sense to me.

We can probably add it to the default ignore file depending on the VCS used.

**Comment by mkovaxx** [comment]
Thanks for the reply here! :)
