### ISSUE TITLE
`cargo component build --workspace` generates `bindings.rs` for non-WIT members

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/cargo-component#258]
Hi folks,

I've got `cargo` workspace with a mix of libraries and wit-components.

`cargo component build --workspace` _used to_ only generate `bindings.rs` for WIT components, but since recent versions (I want to say `v0.9` and later) it seems to build one for every member (even the non-WIT crates)

**Comment by peterhuene** [comment]
This is a regression unless the `Cargo.toml` of those projects contain a `[package.metadata.component]` section or a `wit` directory inside them.

**Comment by peterhuene** [comment]
I see the problem and I'll have a fix tomorrow in a patch release.

**Comment by peterhuene** [comment]
I've released `0.10.1` to fix this issue. If you're already using `0.9.0`, it will hopefully be a pain-free upgrade as there were no breaking changes between those releases except for the newer `warg` component registry support (which no one is yet using).
