### ISSUE TITLE
Hello world example fails when project name contains underscore

### ISSUE THREAD

**Issue by FrankReh** [bytecodealliance/cargo-component#272]
I haven't diagnosed this. But with a new cargo-component installed (v0.11.0), calling `cargo component new hello` builds a cargo directory within which `cargo component build` succeeds but if `cargo component new hello_world` is used, the build step then does not succeed.

```bash
try $ cargo component new hello_world
     Created binary (application) `hello_world` package
     Updated manifest of package `hello_world`
   Generated source file `src/main.rs`
 try $ cd hello_world
 hello_world $ cargo component build
  Generating bindings for hello_world (src/bindings.rs)
   Compiling wit-bindgen-rt v0.24.0
   Compiling bitflags v2.5.0
   Compiling hello_world v0.1.0 (/Users/frank/wasm/try/hello_world)
    Finished dev [unoptimized + debuginfo] target(s) in 0.50s
    Creating component target/wasm32-wasi/debug/hello_world.wasm
error: decoding custom section component-type:wit-bindgen:0.24.0:hello_world:encoded world

Caused by:
    export name `component:hello_world/hello_world` is not a valid extern name
    expected `/` after package name (at offset 0x26)
```

**Comment by rylev** [comment]
I took a very quick look at this, and I can reproduce using the instructions given with the version of cargo-component on main. The issue only seems to be impacting application binaries and not libraries. Specifically the wit metadata seems to not be appropriately munged and ends up using the underscore (which is not valid). This should be detected and replaced with ` -` the way that this is done for `[package.metadata.component.package]` in the Cargo.toml manifest.
