### ISSUE TITLE
Additional `import`s in generated component

### ISSUE THREAD

**Issue by kaivol** [bytecodealliance/cargo-component#282]
A WebAssembly component generated with `cargo-component` has additional imports not mentioned in the `world.wit` (I suspect because of the Rust standard library?), namely
````
wasi:cli/environment@0.2.0;
wasi:cli/exit@0.2.0;
wasi:io/error@0.2.0;
wasi:io/streams@0.2.0;
wasi:cli/stdin@0.2.0;
wasi:cli/stdout@0.2.0;
wasi:cli/stderr@0.2.0;
wasi:clocks/wall-clock@0.2.0;
wasi:filesystem/types@0.2.0;
wasi:filesystem/preopens@0.2.0;
````
That came as a surprise to me when I tried to run the component in `Wasmtime` (without including `wasmtime_wasi`):
```
Error: component imports instance `wasi:cli/environment@0.2.0`, but a matching implementation was not found in the linker
```
Maybe I missed it, but I think this behavior is not documented in the README, in which case I would suggest mentioning it somewhere. 

Also, I was wondering if it is possible to avoid these additional imports, possibly by using `#![no_std]` and thus not linking `libstd`..?

**Comment by peterhuene** [comment]
You are correct that, by default, certain WASI interfaces are automatically imported based upon the component's use of the Rust stdlib.

It is possible to avoid this by not using the `wasm32-wasi` target (which is the [default target of `cargo-component`](https://github.com/bytecodealliance/cargo-component?tab=readme-ov-file#wasi-support)).

If you pass `--target wasm32-unknown-unknown`, the component will not import any WASI interfaces, by default, but it still may import any WASI interfaces that were explicitly imported by the target world.
