### ISSUE TITLE
question: is it possible to further shrink wasm size using `wasm-opt`?

### ISSUE THREAD

**Issue by chaosprint** [bytecodealliance/cargo-component#310]
I just got a 1MB sized wasm, which might be too big for my application.

**Comment by chaosprint** [comment]
Got answer from @alexcrichton in Zulip that `wasm-opt` does not support component model for now

**Comment by calvinrp** [comment]
@chaosprint `jco opt` subcommand feeds each core Wasm into wasm-opt and then puts it back together as a component. 

https://github.com/bytecodealliance/jco/

**Comment by chaosprint** [comment]
> @chaosprint `jco opt` subcommand feeds each core Wasm into wasm-opt and then puts it back together as a component.
> 
> https://github.com/bytecodealliance/jco/

works like a charm. thank you!
