### ISSUE TITLE
How to use `cargo component serve`?

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/cargo-component#311]
I was looking into https://github.com/sunfishcode/hello-wasi-http/issues/14 after https://github.com/bytecodealliance/cargo-component/pull/305 had been merged, and I'm not sure how to use `cargo component serve`? It assumes a binary package, but I don't know how to spell the `fn main` function?

Is there a working example of this available somewhere to reference?

**Comment by calvinrp** [comment]
@yoshuawuyts yeah, I'll follow up with an example. Glad you are experimenting with it. Just boarded a flight. Follow up very soon.

**Comment by calvinrp** [comment]
Commented on https://github.com/sunfishcode/hello-wasi-http/issues/14#issuecomment-2155383527

Worthwhile adding examples in this repo, so we should keep this issue open to track that.

**Comment by yoshuawuyts** [comment]
managed to get this to work! - I think I got something wrong with `main.rs` vs `lib.rs` or `cdylib` not being properly configured.
