### ISSUE TITLE
The binary rules got violated

### ISSUE THREAD

**Issue by dannypsnl** [bytecodealliance/cargo-component#350]
I found an example (https://github.com/sunfishcode/hello-wasi-http) that violates import/export name rules
```bnf
importname' ::= 0x00 len:<u32> in:<importname>                       => in  (if len = |in|)
exportname' ::= 0x00 len:<u32> en:<exportname>                       => en  (if len = |en|)
```
The problem part is pointed out as below:
```
0x1a | 01 13 77 61 | [instance 0] ComponentImport { name: ComponentImportName("wasi:io/error@0.2.0"), ty: Instance(0) }

0x215de2 | 00 1c 69 6d | [type 0] ComponentImport { name: ComponentImportName("import-type-incoming-request"), ty: Type(SubResource) }
```
At `0x1a` it uses old encoding, meanwhile, at `0x215de2` it uses the rule as document.

---

Tools version
- cargo-component-component 0.18.0
- wit-bindgen-rt = { version = "0.35.0", features = ["bitflags"] }

**Comment by sunfishcode** [comment]
This is related to the binary format change in https://github.com/WebAssembly/component-model/pull/263. It appears something is still writing out old-style component import section entries that start with 0x01.

**Comment by sunfishcode** [comment]
It appears cargo-component 0.18 is using an older version of wasm-encoder. I've now submitted https://github.com/bytecodealliance/cargo-component/pull/352 to fix this.
