### ISSUE TITLE
Target wasm32-wasi by default

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/cargo-component#48]
We should switch from targeting `wasm32-unknown-unknown` and target `wasm32-wasi` by default and automatically link in an adapter for users (at least until preview2 is supported natively in the rust toolchain).

**Comment by jeffparsons** [comment]
> at least until preview2 is supported natively in the rust toolchain

Out of curiosity, is anybody working on this already, or is preview2 still too far out for that to make sense yet?

**Comment by sunfishcode** [comment]
> > at least until preview2 is supported natively in the rust toolchain
> 
> Out of curiosity, is anybody working on this already, or is preview2 still too far out for that to make sense yet?

See https://github.com/rust-lang/compiler-team/issues/594 which was just posted 😃

**Comment by jeffparsons** [comment]
Oooh, that is exciting!
