### ISSUE TITLE
Is it possible to make a library that wraps a component implementation?

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/cargo-component#75]
Say I have a component interface that is slightly too low-level for the data I would like to pass between my components: maybe it's a `HashMap` somewhere that I'd like to pass and have to pass as a `Vec` of pairs, because there's no concept mapping to hashmaps afaik in wit. So I would like to have a high-level library that wraps the implementation of a component interface, and then one or several Rust packages would use this library to implement the underlying component. I would like to be able to use `cargo-component`, for this.

I've tried putting the `Cargo.toml` annotations defining that the lib "implements a component when used" to my library crate's TOML, but then `cargo-component` can't find the output: `failed to find output for component package *libhighlevel*`. And it's right: there's no output, it's a lib; the real output would be the package using that library.

Is this something that's possible to do, as of today?

**Comment by peterhuene** [comment]
It's not currently possible as the tool assumes that every Rust package with component metadata should have a component output.

There might be a few places where we're not expecting things to work this way, but on the surface I don't think it would be that hard to implement.

To be clear, you're talking about having a Rust package that has metadata in `Cargo.toml` to provide it some bindings, but have it produce an rlib that can be linked into some other bin/cdylib package that ultimately outputs a component?

**Comment by bnjbvr** [comment]
Thanks for your answer!

> To be clear, you're talking about having a Rust package that has metadata in Cargo.toml to provide it some bindings, but have it produce an rlib that can be linked into some other bin/cdylib package that ultimately outputs a component?

I think so, but I'm not very confident in my knowledge of what's an rlib; if that's what's generated when I do `cargo init --lib`, then yes. Trying to reformulate: I'd like the lib to provide a ready-to-be-customized implementation of the wit interface as a Rust guest, then when that library is used by a Rust package compiled to wasm, the package would output a wasm component.

**Comment by peterhuene** [comment]
For the feature request, I think it would be along the lines of:

1. Allow component metadata in `lib` packages that aren't `cdylib`; only generate bindings.
2. Do not attempt to componentize the output of such packages (i.e. there is no `.wasm` output).
3. Ensure that linking in multiple custom sections containing wit-bindgen metadata sourced from those rlibs is properly combined when linking the final component.
