### ISSUE TITLE
Required protoc version is confusing

### ISSUE THREAD

**Issue by mstolin** [bytecodealliance/cargo-component#81]
The readme states to install `a protobuf compiler of version 3.15 or greater`. However, when I install `protoc` as instructed at http://google.github.io/proto-lens/installing-protoc.html, and afterward install cargo component, I get the following error:

```sh
error: failed to run custom build command for `warg-transparency v0.1.0 (https://github.com/bytecodealliance/registry#9d9e4b17)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installGXyW0h/release/build/warg-transparency-964a17dd4eb3e10f/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Building this crate requires a version of protoc (libprotoc) >=15.0, found: libprotoc 3.15.8

  Please install a suitable version of protobuf (see https://github.com/protocolbuffers/protobuf for downloads and instructions as well as https://protobuf.dev/support/version-support/ for info on protobuf's versioning schema)', cargo/git/checkouts/registry-c434769d228bc60a/9d9e4b1/crates/transparency/build.rs:57:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
So the error message tells me to install `protoc` of version >= 15.

I was able to overcome this error, by downloading a protoc binary from https://github.com/protocolbuffers/protobuf/releases and move that to my `bin` folder instead.

**Comment by peterhuene** [comment]
The error message in question comes from the [build script](https://github.com/bytecodealliance/registry/blob/65659774e44742a5a6cf0da8943fbc310b12cae9/crates/protocol/build.rs#L58) of `warg-protocol`, which isn't in this repository.

It appears the script was updated recently to accommodate changes to `protoc` versions and we're now using the latest out of the registry repo.

I'm going to close this issue for now but if you continue to run into problems, please open an issue in the https://github.com/bytecodealliance/registry repo.
