### ISSUE TITLE
Latest version of wasm-tools breaks cargo-component output

### ISSUE THREAD

**Issue by patrickhuber** [bytecodealliance/cargo-component#82]
[Wasm-tools release 1.0.35](https://github.com/bytecodealliance/wasm-tools/releases/tag/wasm-tools-1.0.35) bumped the [wit-component crate](https://crates.io/crates/wit-component) to version 0.11.0 which breaks compatibility with cargo-component. 

Trying to run a `wasm-tools parse` command on the results of `cargo component build` produces an error:

```
error: invalid leading byte (0xc) for import name (at offset 0x11)
```

Steps to reproduce:

* Install wasm-tools version wasm-tools-1.0.35
* Install cargo-component
* Create a component with `cargo component new --lib demo`
* Run `cd demo; cargo build`
* Run `wasm-tools parse -t target/wasm32-wasi/debug/demo.wasm `
* Observe error above
* Install wasm-tools version wasm-tools-1.0.34
* Run `wasm-tools parse -t target/wasm32-wasi/debug/demo.wasm`
* Observe wat output of wasm file

**Comment by peterhuene** [comment]
Hi @patrickhuber, thanks for the issue!

I'm currently working on updating `cargo-component` to the latest dependencies to get it working with the binary format changes; there should be a PR soon.

**Comment by Kylebrown9** [comment]
Was the binary format version bumped in a way that we could detect/report better in the future?

**Comment by peterhuene** [comment]
I think the installed `wasm-tools` from above is out of date, the expected message should be: `unknown component version: 0xd`

**Comment by peterhuene** [comment]
Oh right, `wasmprinter` doesn't intentionally validate (so that it can print "the best it can") and that error would originate from the validator.
