### ISSUE TITLE
Installing with `cargo install --path .` fails with weird error

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/cargo-component#84]
This commit in the registry broke installing `cargo-component`: https://github.com/bytecodealliance/registry/commit/65659774e44742a5a6cf0da8943fbc310b12cae9

Would you be open to pin the `warg-*` git commit to specific commits? That would help get rid of this kind of errors, and make sure that updates of cargo-component's dependencies are under control.

## STR

- `cargo install --path .`

## Observed

```
error[E0432]: unresolved import `warg_crypto::hash::DynHash`
  --> src/registry.rs:27:25
   |
27 | use warg_crypto::hash::{DynHash, Sha256};
   |                         ^^^^^^^
   |                         |
   |                         no `DynHash` in `hash`
   |                         help: a similar name exists in the module: `AnyHash`

error[E0063]: missing field `head` in initializer of `PublishInfo`
   --> src/lib.rs:403:20
    |
403 |     let mut info = PublishInfo {
    |                    ^^^^^^^^^^^ missing `head`

error[E0063]: missing field `head` in initializer of `PublishInfo`
   --> src/lib.rs:524:20
    |
524 |     let mut info = PublishInfo {
    |                    ^^^^^^^^^^^ missing `head`

Some errors have detailed explanations: E0063, E0432.
For more information about an error, try `rustc --explain E0063`.
error: could not compile `cargo-component` due to 3 previous errors
error: failed to compile `cargo-component v0.1.0 (/home/ben/code/cargo-component)`, intermediate artifacts can be found at `/home/ben/code/cargo-component/target`
```

**Comment by peterhuene** [comment]
The crates are already locked to specific commits, it's just that `cargo install` ignores the lock file by default to ensure it is installed with the latest dependencies.

Until such time as the warg crates are published (with semver), you'll need to pass `--locked` when installing.

**Comment by bnjbvr** [comment]
Thanks, indeed it solves my issue in the meanwhile.
